import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsAr: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "لنبدأ!",
  [BTN.Im_Smoking]: "أنا أدخّن 🚬 (Legacy)",
  [BTN.Im_Smoking_1]: "أنا أدخّن 🚬",
  [BTN.Im_Smoking_2]: "أنا أدخّن 🚬 ",
  [BTN.Im_Smoking_3]: "أنا أدخّن 🚬  ",
  [BTN.Forgot_To_Use_Smoking_Button]: "نسيت الضغط 🫤",
  [BTN.Reset_Stage_1]: "ابدأ من جديد 👍",
  [BTN.Reset_Stage_2]: "إعادة التعيين إلى المرحلة الثانية 🐯",
  [BTN.Reset_Ignore]: "إبقاء الأمور كما هي ❌️",
  [BTN.Level_Easy]: "وضع التدريب 📚",
  [BTN.Level_Easy_Ignore]: "استمر ❌️",
  [BTN.Level_Medium]: "عادي 👍",
  [BTN.Level_Hard]: "سريع 👑",
  [BTN.Level_Keep_As_It_Is]: "لا تغيير 📚",
  [BTN.Level_Change]: "رفع المستوى 🥇",
  [BTN.Ignore_Success]: "أقلعت!",
  [BTN.Ignore_Failed]: "لن أقلع 👎",
  [BTN.Ignore_Full_Reset]: "من البداية 🔄",
  [BTN.Ignore_Just_Go_On]: "استمر 👌",
  [BTN.Ignore_Set_Own_Interval]: "فترتي الخاصة 🔻",
  [BTN.Local_Time_Correct]: "صحيح ✅",
  [BTN.Local_Time_Wrong]: "✏️ تعديل",
  [BTN.Local_Time_Plus_1]: "+ ساعة",
  [BTN.Local_Time_Minus_1]: "- ساعة",
  [BTN.Local_Time_Plus_30]: "+ 30 دقيقة",
  [BTN.Local_Time_Minus_30]: "- 30 دقيقة",
  [BTN.Local_Time_AmPm]: "AM/PM",
  [BTN.Local_Time_24h]: "24 ساعة",
  [BTN.Local_Time_Confirmed]: "الوقت صحيح 👍",
  [BTN.Recommendations]: "نصائح للإقلاع عن التدخين",
  [BTN.Pro_Next_Day]: "ابدأ يومًا جديدًا 🪐",
  [BTN.Pro_This_Day]: "استمر ▶️",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Lang_ES]: "ES 🇪🇸",
  [BTN.Lang_DE]: "DE 🇩🇪",
  [BTN.Lang_IT]: "IT 🇮🇹",
  [BTN.Lang_TR]: "TR 🇹🇷",
  [BTN.Lang_ZH]: "ZH 🇨🇳",
  [BTN.Lang_AR]: "AR 🇸🇦",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  [BTN.Dev_Delete_User]: "Delete user 🗑️",
  [BTN.Dev_To_Stage_1]: "Reset to Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Fill Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time to 1 hour ago 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 more than max 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "By timer ⏰️",
  [BTN.Dev_Next_Failed]: "By timer (failed) ⏰️",
  [BTN.Dev_Motivizer_25]: "Motivizer to 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Motivizer full ⛹️",
  [BTN.Dev_Ignore]: "To Ignore Mode 🌀",
  [BTN.Dev_Content]: "Content 📋",
  [BTN.Dev_Content_All]: "All Content 📋",
};
