import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsTr: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "Başlayalım!",
  [BTN.Im_Smoking]: "Sigara içiyorum 🚬 (Legacy)",
  [BTN.Im_Smoking_1]: "Sigara içiyorum 🚬",
  [BTN.Im_Smoking_2]: "Sigara içiyorum 🚬 ",
  [BTN.Im_Smoking_3]: "Sigara içiyorum 🚬  ",
  [BTN.Forgot_To_Use_Smoking_Button]: "Basmayı unuttum 🫤",
  [BTN.Reset_Stage_1]: "Baştan başla 👍",
  [BTN.Reset_Stage_2]: "Aşama 2'ye sıfırla 🐯",
  [BTN.Reset_Ignore]: "Olduğu gibi bırak ❌️",
  [BTN.Level_Easy]: "Antrenman modu 📚",
  [BTN.Level_Easy_Ignore]: "Devam et ❌️",
  [BTN.Level_Medium]: "Normal 👍",
  [BTN.Level_Hard]: "Hızlı 👑",
  [BTN.Level_Keep_As_It_Is]: "Değiştirme 📚",
  [BTN.Level_Change]: "Seviyeyi yükselt 🥇",
  [BTN.Ignore_Success]: "Bıraktım!",
  [BTN.Ignore_Failed]: "Bırakmayacağım 👎",
  [BTN.Ignore_Full_Reset]: "Baştan başla 🔄",
  [BTN.Ignore_Just_Go_On]: "Devam et 👌",
  [BTN.Ignore_Set_Own_Interval]: "Kendi aralığım 🔻",
  [BTN.Local_Time_Correct]: "Doğru ✅",
  [BTN.Local_Time_Wrong]: "✏️ Düzenle",
  [BTN.Local_Time_Plus_1]: "+ 1 saat",
  [BTN.Local_Time_Minus_1]: "- 1 saat",
  [BTN.Local_Time_Plus_30]: "+ 30 dakika",
  [BTN.Local_Time_Minus_30]: "- 30 dakika",
  [BTN.Local_Time_AmPm]: "AM/PM",
  [BTN.Local_Time_24h]: "24s",
  [BTN.Local_Time_Confirmed]: "Saat doğru 👍",
  [BTN.Recommendations]: "Sigarayı bırakma ipuçları",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Lang_ES]: "ES 🇪🇸",
  [BTN.Lang_DE]: "DE 🇩🇪",
  [BTN.Lang_IT]: "IT 🇮🇹",
  [BTN.Lang_TR]: "TR 🇹🇷",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  [BTN.Dev_Delete_User]: "Delete user 🗑️",
  [BTN.Dev_To_Stage_1]: "Reset to Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Fill Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time to 1 hour ago 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 more than max 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "By timer ⏰️",
  [BTN.Dev_Next_Failed]: "By timer (failed) ⏰️",
  [BTN.Dev_Motivizer_25]: "Motivizer to 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Motivizer full ⛹️",
  [BTN.Dev_Ignore]: "To Ignore Mode 🌀",
  [BTN.Dev_Content]: "Content 📋",
  [BTN.Dev_Content_All]: "All Content 📋",
};
