import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsEs: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "¡Empecemos!",
  [BTN.Im_Smoking]: "Estoy fumando 🚬 (Legacy)",
  [BTN.Im_Smoking_1]: "Estoy fumando 🚬",
  [BTN.Im_Smoking_2]: "Estoy fumando 🚬 ",
  [BTN.Im_Smoking_3]: "Estoy fumando 🚬  ",
  [BTN.Forgot_To_Use_Smoking_Button]: "Olvidé pulsar 🫤",
  [BTN.Reset_Stage_1]: "Reiniciar todo 👍",
  [BTN.Reset_Stage_2]: "Reiniciar a Etapa 2 🐯",
  [BTN.Reset_Ignore]: "Dejar como está ❌️",
  [BTN.Level_Easy]: "Modo entrenamiento 📚",
  [BTN.Level_Easy_Ignore]: "Continuar ❌️",
  [BTN.Level_Medium]: "Normal 👍",
  [BTN.Level_Hard]: "Rápido 👑",
  [BTN.Level_Keep_As_It_Is]: "No cambiar 📚",
  [BTN.Level_Change]: "Subir nivel 🥇",
  [BTN.Ignore_Success]: "¡Dejé de fumar!",
  [BTN.Ignore_Failed]: "No voy a dejar 👎",
  [BTN.Ignore_Full_Reset]: "Desde el principio 🔄",
  [BTN.Ignore_Just_Go_On]: "Simplemente continuar 👌",
  [BTN.Ignore_Set_Own_Interval]: "Tu tiempo 🔻",
  [BTN.Local_Time_Correct]: "Correcto ✅",
  [BTN.Local_Time_Wrong]: "✏️ Cambiar",
  [BTN.Local_Time_Plus_1]: "+ 1 hora",
  [BTN.Local_Time_Minus_1]: "- 1 hora",
  [BTN.Local_Time_Plus_30]: "+ 30 minutos",
  [BTN.Local_Time_Minus_30]: "- 30 minutos",
  [BTN.Local_Time_AmPm]: "AM/PM",
  [BTN.Local_Time_24h]: "24h",
  [BTN.Local_Time_Confirmed]: "La hora es correcta 👍",
  [BTN.Recommendations]: "Consejos para dejar de fumar",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Lang_ES]: "ES 🇪🇸",
  [BTN.Lang_DE]: "DE 🇩🇪",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  [BTN.Dev_Content_ES]: "ES 🇪🇸",
  [BTN.Dev_Content_DE]: "DE 🇩🇪",
  [BTN.Dev_Delete_User]: "Delete user 🗑️",
  [BTN.Dev_To_Stage_1]: "Reset to Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Fill Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time to 1 hour ago 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 more than max 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "By timer ⏰️",
  [BTN.Dev_Next_Failed]: "By timer (failed) ⏰️",
  [BTN.Dev_Motivizer_25]: "Motivizer to 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Motivizer full ⛹️",
  [BTN.Dev_Ignore]: "To Ignore Mode 🌀",
  [BTN.Dev_Content]: "Content 📋",
  [BTN.Dev_Content_All]: "All Content 📋",
};
