import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsZh: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "开始！",
  [BTN.Im_Smoking]: "我在吸烟 🚬 (Legacy)",
  [BTN.Im_Smoking_1]: "我在吸烟 🚬",
  [BTN.Im_Smoking_2]: "我在吸烟 🚬 ",
  [BTN.Im_Smoking_3]: "我在吸烟 🚬  ",
  [BTN.Forgot_To_Use_Smoking_Button]: "忘记按了 🫤",
  [BTN.Reset_Stage_1]: "从头开始 👍",
  [BTN.Reset_Stage_2]: "重置到第二阶段 🐯",
  [BTN.Reset_Ignore]: "保持原样 ❌️",
  [BTN.Level_Easy]: "训练模式 📚",
  [BTN.Level_Easy_Ignore]: "继续 ❌️",
  [BTN.Level_Medium]: "普通 👍",
  [BTN.Level_Hard]: "快速 👑",
  [BTN.Level_Keep_As_It_Is]: "不更改 📚",
  [BTN.Level_Change]: "提升级别 🥇",
  [BTN.Ignore_Success]: "我戒了！",
  [BTN.Ignore_Failed]: "我不会戒 👎",
  [BTN.Ignore_Full_Reset]: "从头开始 🔄",
  [BTN.Ignore_Just_Go_On]: "继续 👌",
  [BTN.Ignore_Set_Own_Interval]: "自定义间隔 🔻",
  [BTN.Local_Time_Correct]: "正确 ✅",
  [BTN.Local_Time_Wrong]: "✏️ 修改",
  [BTN.Local_Time_Plus_1]: "+ 1 小时",
  [BTN.Local_Time_Minus_1]: "- 1 小时",
  [BTN.Local_Time_Plus_30]: "+ 30 分钟",
  [BTN.Local_Time_Minus_30]: "- 30 分钟",
  [BTN.Local_Time_AmPm]: "AM/PM",
  [BTN.Local_Time_24h]: "24小时制",
  [BTN.Local_Time_Confirmed]: "时间正确 👍",
  [BTN.Recommendations]: "戒烟建议",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Lang_ES]: "ES 🇪🇸",
  [BTN.Lang_DE]: "DE 🇩🇪",
  [BTN.Lang_IT]: "IT 🇮🇹",
  [BTN.Lang_TR]: "TR 🇹🇷",
  [BTN.Lang_ZH]: "ZH 🇨🇳",
  [BTN.Lang_AR]: "AR 🇸🇦",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  [BTN.Dev_Delete_User]: "Delete user 🗑️",
  [BTN.Dev_To_Stage_1]: "Reset to Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Fill Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time to 1 hour ago 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 more than max 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "By timer ⏰️",
  [BTN.Dev_Next_Failed]: "By timer (failed) ⏰️",
  [BTN.Dev_Motivizer_25]: "Motivizer to 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Motivizer full ⛹️",
  [BTN.Dev_Ignore]: "To Ignore Mode 🌀",
  [BTN.Dev_Content]: "Content 📋",
  [BTN.Dev_Content_All]: "All Content 📋",
};
