import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsRu: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "Начинаем!",
  [BTN.Im_Smoking]: "Я сейчас курю 🚬 (Legacy)",
  [BTN.Im_Smoking_1]: "Я сейчас курю 🚬",
  [BTN.Im_Smoking_2]: "Я сейчас курю 🚬 ",
  [BTN.Im_Smoking_3]: "Я сейчас курю 🚬  ",
  [BTN.Forgot_To_Use_Smoking_Button]: "Забыл нажать 🫤",
  [BTN.Reset_Stage_1]: "Сбросить всё 👍",
  [BTN.Reset_Stage_2]: "Сбросить до Этапа 2 🐯",
  [BTN.Reset_Ignore]: "Оставить \"как есть\" ❌️",
  [BTN.Level_Easy]: "Тренировочный режим 📚",
  [BTN.Level_Easy_Ignore]: "Продолжим ❌️",
  [BTN.Level_Medium]: "Обычный 👍",
  [BTN.Level_Hard]: "Быстрый 👑",
  [BTN.Level_Keep_As_It_Is]: "Не меняем 📚",
  [BTN.Level_Change]: "Поднять уровень 🥇",
  [BTN.Ignore_Success]: "Я бросил!",
  [BTN.Ignore_Failed]: "Не буду бросать 👎",
  [BTN.Ignore_Full_Reset]: "С самого начала 🔄",
  [BTN.Ignore_Just_Go_On]: "Просто продолжим 👌",
  [BTN.Ignore_Set_Own_Interval]: "Ваше время 🔻",
  [BTN.Local_Time_Correct]: "Верно ✅",
  [BTN.Local_Time_Wrong]: "✏️ Изменить",
  [BTN.Local_Time_Plus_1]: "+ 1 час",
  [BTN.Local_Time_Minus_1]: "- 1 час",
  [BTN.Local_Time_Plus_30]: "+ 30 минут",
  [BTN.Local_Time_Minus_30]: "- 30 минут",
  [BTN.Local_Time_AmPm]: "AM/PM формат",
  [BTN.Local_Time_24h]: "24h формат",
  [BTN.Local_Time_Confirmed]: "Время установлено верно 👍",
  [BTN.Recommendations]: "Советы, как бросить курить",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Lang_ES]: "ES 🇪🇸",
  [BTN.Lang_DE]: "DE 🇩🇪",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  [BTN.Dev_Delete_User]: "Удалить пользователя 🗑️",
  [BTN.Dev_To_Stage_1]: "Сбросить до Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Заполнить Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time на 1 час назад 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 больше макс 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "По таймеру ⏰️",
  [BTN.Dev_Next_Failed]: "По таймеру (failed) ⏰️",
  [BTN.Dev_Motivizer_25]: "Мотивайзер на 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Мотивайзер весь ⛹️",
  [BTN.Dev_Ignore]: "В режим Ignore 🌀",
  [BTN.Dev_Content]: "Контент 📋",
  [BTN.Dev_Content_All]: "Весь контент 📋",
};