import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsIt: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "Iniziamo!",
  [BTN.Im_Smoking]: "Sto fumando 🚬 (Legacy)",
  [BTN.Im_Smoking_1]: "Sto fumando 🚬",
  [BTN.Im_Smoking_2]: "Sto fumando 🚬 ",
  [BTN.Im_Smoking_3]: "Sto fumando 🚬  ",
  [BTN.Forgot_To_Use_Smoking_Button]: "Ho dimenticato di premere 🫤",
  [BTN.Reset_Stage_1]: "Ricomincia da capo 👍",
  [BTN.Reset_Stage_2]: "Reimposta alla Fase 2 🐯",
  [BTN.Reset_Ignore]: "Lascia com'è ❌️",
  [BTN.Level_Easy]: "Modalità allenamento 📚",
  [BTN.Level_Easy_Ignore]: "Continua ❌️",
  [BTN.Level_Medium]: "Normale 👍",
  [BTN.Level_Hard]: "Veloce 👑",
  [BTN.Level_Keep_As_It_Is]: "Non cambiare 📚",
  [BTN.Level_Change]: "Aumenta livello 🥇",
  [BTN.Ignore_Success]: "Ho smesso!",
  [BTN.Ignore_Failed]: "Non smetterò 👎",
  [BTN.Ignore_Full_Reset]: "Dall'inizio 🔄",
  [BTN.Ignore_Just_Go_On]: "Continua semplicemente 👌",
  [BTN.Ignore_Set_Own_Interval]: "Il tuo tempo 🔻",
  [BTN.Local_Time_Correct]: "Corretto ✅",
  [BTN.Local_Time_Wrong]: "✏️ Modifica",
  [BTN.Local_Time_Plus_1]: "+ 1 ora",
  [BTN.Local_Time_Minus_1]: "- 1 ora",
  [BTN.Local_Time_Plus_30]: "+ 30 minuti",
  [BTN.Local_Time_Minus_30]: "- 30 minuti",
  [BTN.Local_Time_AmPm]: "AM/PM",
  [BTN.Local_Time_24h]: "24h",
  [BTN.Local_Time_Confirmed]: "L'orario è corretto 👍",
  [BTN.Recommendations]: "Consigli per smettere di fumare",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Lang_ES]: "ES 🇪🇸",
  [BTN.Lang_DE]: "DE 🇩🇪",
  [BTN.Lang_IT]: "IT 🇮🇹",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  [BTN.Dev_Delete_User]: "Delete user 🗑️",
  [BTN.Dev_To_Stage_1]: "Reset to Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Fill Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time to 1 hour ago 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 more than max 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "By timer ⏰️",
  [BTN.Dev_Next_Failed]: "By timer (failed) ⏰️",
  [BTN.Dev_Motivizer_25]: "Motivizer to 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Motivizer full ⛹️",
  [BTN.Dev_Ignore]: "To Ignore Mode 🌀",
  [BTN.Dev_Content]: "Content 📋",
  [BTN.Dev_Content_All]: "All Content 📋",
};
