import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsDe: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "Los geht's!",
  [BTN.Im_Smoking]: "Ich rauche gerade 🚬 (Legacy)",
  [BTN.Im_Smoking_1]: "Ich rauche gerade 🚬",
  [BTN.Im_Smoking_2]: "Ich rauche gerade 🚬 ",
  [BTN.Im_Smoking_3]: "Ich rauche gerade 🚬  ",
  [BTN.Forgot_To_Use_Smoking_Button]: "Vergessen zu drücken 🫤",
  [BTN.Reset_Stage_1]: "Alles zurücksetzen 👍",
  [BTN.Reset_Stage_2]: "Auf Stufe 2 zurücksetzen 🐯",
  [BTN.Reset_Ignore]: "So lassen wie es ist ❌️",
  [BTN.Level_Easy]: "Trainingsmodus 📚",
  [BTN.Level_Easy_Ignore]: "Weiter ❌️",
  [BTN.Level_Medium]: "Normal 👍",
  [BTN.Level_Hard]: "Schnell 👑",
  [BTN.Level_Keep_As_It_Is]: "Nicht ändern 📚",
  [BTN.Level_Change]: "Level erhöhen 🥇",
  [BTN.Ignore_Success]: "Ich habe aufgehört!",
  [BTN.Ignore_Failed]: "Ich werde nicht aufhören 👎",
  [BTN.Ignore_Full_Reset]: "Von vorne anfangen 🔄",
  [BTN.Ignore_Just_Go_On]: "Einfach weitermachen 👌",
  [BTN.Ignore_Set_Own_Interval]: "Eigene Zeit 🔻",
  [BTN.Local_Time_Correct]: "Richtig ✅",
  [BTN.Local_Time_Wrong]: "✏️ Ändern",
  [BTN.Local_Time_Plus_1]: "+ 1 Stunde",
  [BTN.Local_Time_Minus_1]: "- 1 Stunde",
  [BTN.Local_Time_Plus_30]: "+ 30 Minuten",
  [BTN.Local_Time_Minus_30]: "- 30 Minuten",
  [BTN.Local_Time_AmPm]: "AM/PM",
  [BTN.Local_Time_24h]: "24h",
  [BTN.Local_Time_Confirmed]: "Die Zeit ist korrekt 👍",
  [BTN.Recommendations]: "Tipps zum Aufhören",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Lang_ES]: "ES 🇪🇸",
  [BTN.Lang_DE]: "DE 🇩🇪",
  [BTN.Lang_IT]: "IT 🇮🇹",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  // DON'T CREATE ANY NEW DEV BUTTON
  [BTN.Dev_Delete_User]: "Delete user 🗑️",
  [BTN.Dev_To_Stage_1]: "Reset to Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Fill Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time to 1 hour ago 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 more than max 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "By timer ⏰️",
  [BTN.Dev_Next_Failed]: "By timer (failed) ⏰️",
  [BTN.Dev_Motivizer_25]: "Motivizer to 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Motivizer full ⛹️",
  [BTN.Dev_Ignore]: "To Ignore Mode 🌀",
  [BTN.Dev_Content]: "Content 📋",
  [BTN.Dev_Content_All]: "All Content 📋",
};
