export const youcanIt = [
  "Puoi decidere tu stesso quando fumare e quando no.",
  "Devi superare le tue abitudini. Non è difficile.",
  "Puoi saltare una pausa fumo inutile.",
  "Lo stai facendo per le persone care. E per te stesso, prima di tutto.",
  "Non hai fumato DA QUANDO hai iniziato a usare il bot.",
  "Non devi finire la sigaretta se non ne hai voglia.",
  "Il programma delle pause fumo è solo un timer. Se non hai ancora voglia di fumare, non farlo.",
  "In realtà, il desiderio di fumare non dura a lungo. Solo 5–10 minuti.",
  "Aspettare e gestire lo stress è normale. Farlo senza sigarette è normale anche quello.",
  "Siamo stati tutti ingannati dalla pubblicità. È ora di lasciarla andare. Smetti.",
  "Solo lavorando su noi stessi raggiungiamo nuove vette. Stai smettendo — sii orgoglioso di te!",
  "Immagina quanto saranno sorpresi le persone intorno a te quando smetterai.",
  "Un pezzo di foglia avvolto in carta controlla una persona? No!",
  "Limitati ogni giorno. È l'unico modo per superare il fumo.",
  "Molti smettono di fumare solo dopo aver affrontato le conseguenze.",
  "Una volta che decidi tu quando fumare, e non la tua abitudine, non ne sei più schiavo.",
  "Il fumo non calma i nervi. È solo un trucco di marketing.",
  "Non cedere fino alla fine. Né nei giorni di festa, né nei giorni difficili.",
  "Ricorda sempre — smettere di fumare è il tuo obiettivo personale. Sei quasi arrivato.",
  "Hai voglia di fumare? Imposta un timer per 10 minuti. Non ne avrai più voglia — provato e verificato.",
  "Così tanti soldi in fumo...",
  "Quando hai iniziato a usare il bot, hai deciso fermamente di smettere di fumare. Smetti. Ne vale la pena.",
  "Le cattive abitudini sono per le persone deboli di spirito. Non è il tuo caso.",
  "Monitora i tuoi progressi usando il bot. Guarda quanto è cambiato per te in un mese.",
  "La maggior parte delle persone non fuma. Smetti.",
  "Il fumo è un'illusione di relax. In realtà, il tuo corpo soffre per le sue tossine.",
  "Visualizza il negativo. Ricorda cosa ti infastidisce di più del fumo.",
  "Meriti di meglio. Non fumare.",
  "Questo mondo è costruito sulle vite umane ma sostenuto dai risultati umani.",
  "Stai smettendo di fumare! Stai facendo un lavoro straordinario!",
  "La determinazione a combattere le cattive abitudini definisce la persona moderna.",
  "Perché rompere il programma delle pause fumo se dimenticherai di voler fumare in 5 minuti?",
  "Quanto può essere difficile a volte aspettare la prossima pausa fumo...",
  "Un'abitudine strana e inutile plasma il tuo tempo libero?",
  "Gli altri ti guarderanno come un esempio quando smetterai.",
  "Il fumo è un sistema in cui la persona perde sempre.",
  "La forza di volontà è come un muscolo in palestra. Batti il fumo e conquisterai anche altre sfide.",
  "Quando espiri il fumo, non rimane nulla. È solo tempo sprecato.",
  "La dipendenza dalla nicotina è un nemico molto, molto subdolo. Combattila.",
  "Se hai voglia di fumare, prova a pensare a qualcos'altro. Potrebbe aiutare.",
  "Una sigaretta non è il tuo padrone! Se vuoi fumare, fumi; se non vuoi, non fumi!",
  "Perché fumare se semplicemente non ne hai voglia?",
  "Non arrenderti. Un mese o due e non fumerai più. È semplice.",
  "Controlla le tue statistiche di tanto in tanto. È scioccante quanti soldi sono andati in fumo! Comando: /stats",
  "Cosa potresti fare invece di un'altra pausa fumo?",
  "Non sei più un asset dell'azienda tabacchiera.",
  "Il tuo corpo non muore senza nicotina; è solo il tuo cervello che cerca di giocare il suo vecchio trucco su di te.",
  "Ogni volta che rimandi il fumo, la dipendenza perde la sua forza.",
  "Il fumo è solo tossine e zero benefici.",
  "Quando hai deciso di smettere di fumare, hai protetto il tuo futuro.",
  "Il fumo rovina solo tutto. È un'abitudine inutile.",
  "Che tipo di catene decidono che devi inalare fumo?",
  "Pensa a quante persone sono state ingannate dalla pubblicità delle sigarette.",
  "Sei migliore e più forte di una stupida abitudine.",
  "Smettere di fumare è più facile di quanto pensino la maggior parte delle persone.",
  "Vivere intorno a un oggetto che non solo non ti dà nulla ma danneggia anche la tua salute.",
  "Le sigarette distruggono la salute.",
  "Il desiderio di fumare è una debolezza.",
  "Perché un'abitudine dovrebbe dettare il tuo programma? Smetti!",
  "Il fumo è qualcosa che dovrebbe essere lasciato alle spalle.",
].map(content => `🌟 🌟 🌟 🌟 🌟\n_${content}_`);
