export const youcanDe = [
  "Du kannst selbst bestimmen, wann du rauchst und wann nicht.",
  "Du musst deine Gewohnheiten überwinden. Das ist nicht schwer.",
  "Du kannst eine extra Rauchpause auslassen.",
  "Du tust das für deine Lieben. Und in erster Linie für dich selbst.",
  "Du rauchst BEREITS NICHT MEHR — seit du den Bot benutzt.",
  "Es ist nicht nötig, die Zigarette zu Ende zu rauchen, wenn man nicht will.",
  "Der Rauchplan ist nur ein Timer. Wenn du noch keine Lust hast — rauch nicht.",
  "Tatsächlich dauert das Verlangen zu rauchen nicht lange. Nur 5-10 Minuten.",
  "Warten und mit Stress umgehen ist normal. Auch ohne Zigaretten ist das normal.",
  "Wir alle wurden von der Werbung getäuscht. Es ist Zeit, das loszuwerden. Hör auf.",
  "Nur indem wir an uns arbeiten, erreichen wir neue Höhen. Du hörst auf — du hast Grund, stolz zu sein!",
  "Stell dir vor, wie überrascht andere sein werden, wenn du aufhörst.",
  "Ein Stück Blatt in Papier gewickelt kontrolliert einen Menschen? Nein!",
  "Schränke dich jeden Tag ein. Nur so kann man das Rauchen besiegen.",
  "Viele hören auf zu rauchen, wenn sie bereits mit den Folgen konfrontiert sind.",
  "Sobald du selbst entscheidest, wann du rauchst, und nicht die Gewohnheit — bist du nicht mehr ihr Sklave.",
  "Rauchen beruhigt die Nerven nicht. Das ist ein gewöhnlicher Werbetrick.",
  "Gib dir keine Schwäche bis zum Schluss. Weder an Feiertagen noch an schweren Werktagen.",
  "Denk immer daran — mit dem Rauchen aufzuhören ist dein persönliches Ziel. Es ist schon nah.",
  "Lust zu rauchen? Stell einen Timer auf 10 Minuten. Die Lust vergeht — bewährt.",
  "So viel Geld in Rauch...",
  "Als du anfingst, den Bot zu benutzen, hast du fest entschieden, mit dem Rauchen aufzuhören. Hör auf. Es lohnt sich.",
  "Schlechte Gewohnheiten sind das Los schwacher Menschen. Das bist nicht du.",
  "Beobachte deinen Fortschritt mit dem Bot. Wie sehr hat sich alles für dich in einem Monat verändert.",
  "Die meisten Menschen sind Nichtraucher. Hör auf.",
  "Rauchen ist eine Illusion der Entspannung. Deinem Körper geht es durch seine Gifte tatsächlich schlecht.",
  "Visualisiere das Negative. Erinnere dich, was dich am Rauchen am meisten stört.",
  "Du verdienst Besseres. Rauch nicht.",
  "Diese ganze Welt ist auf menschlichen Leben aufgebaut. Aber sie hält sich durch menschliche Errungenschaften.",
  "Du hörst auf zu rauchen! Du bist großartig!",
  "Die Entschlossenheit, schlechte Gewohnheiten zu bekämpfen, definiert den modernen Menschen.",
  "Warum den Rauchplan brechen, wenn du in 5 Minuten vergessen hast, dass du rauchen wolltest?",
  "Manchmal ist es so schwer, auf die nächste Rauchpause zu warten...",
  "Eine seltsame und nutzlose Gewohnheit bestimmt deine Freizeit?",
  "Andere werden auf dich als Vorbild schauen, wenn du aufhörst.",
  "Rauchen ist ein System, bei dem der Mensch immer verliert.",
  "Willenskraft ist wie ein Muskel im Fitnessstudio. Wenn du das Rauchen besiegst, kannst du auch andere Dinge besiegen.",
  "Wenn du den Rauch ausatmest, bleibt nichts übrig. Nur vergeudete Zeit.",
  "Nikotinsucht ist ein sehr, sehr listiger Feind. Kämpfe.",
  "Wenn du rauchen willst — versuche, an etwas anderes zu denken. Vielleicht hilft es.",
  "Die Zigarette ist nicht dein Herr! Willst du — rauchst du, willst du nicht — rauchst du nicht!",
  "Warum rauchen, wenn man einfach keine Lust hat?",
  "Gib nicht auf. Ein bis zwei Monate und du rauchst nicht mehr. Das ist einfach.",
  "Schau manchmal in die Statistik. Es ist erschreckend, wie viel Geld in Rauch aufgegangen ist! Befehl /stats",
  "Was könnte man statt einer weiteren Rauchpause tun?",
  "Du bist kein Aktivposten der Tabakfirma mehr.",
  "Dein Körper stirbt nicht ohne Nikotin, das ist nur dein Gehirn, das sein altes Spiel mit dir spielt.",
  "Jedes Mal, wenn du das Rauchen aufschiebt, verliert die Sucht ihre Kraft.",
  "Rauchen sind nur Toxine und null Nutzen.",
  "Als du entschieden hast, mit dem Rauchen aufzuhören, hast du deine Zukunft geschützt.",
  "Rauchen verdirbt alles. Nutzlose Gewohnheit.",
  "Was sind das für Ketten, die entscheiden, dass du rauchen musst?",
  "Denk daran, wie viele Menschen von der Zigarettenwerbung getäuscht wurden.",
  "Du bist besser und stärker als eine dumme Gewohnheit.",
  "Mit dem Rauchen aufzuhören ist einfacher, als viele Menschen denken.",
  "Das Leben um einen Gegenstand herum, der nicht nur nichts bringt, sondern die Gesundheit ruiniert.",
  "Zigaretten zerstören die Gesundheit.",
  "Das Verlangen zu rauchen ist Schwäche.",
  "Warum sollte eine Gewohnheit den Zeitplan deines Tages bestimmen? Hör auf!",
  "Rauchen ist etwas, das man hinter sich lassen muss.",
].map(content => `🌟 🌟 🌟 🌟 🌟\n_${content}_`);
