export const youcanTr = [
  "Ne zaman sigara içeceğinize kendiniz karar verebilirsiniz.",
  "Alışkanlıklarınızın üstesinden gelmelisiniz. Bu zor değil.",
  "Gereksiz bir sigara molasını atlayabilirsiniz.",
  "Bunu sevdikleriniz için yapıyorsunuz. Ve her şeyden önce kendiniz için.",
  "Botu kullanmaya başladığınızdan beri sigara içmediniz.",
  "İstemiyorsanız sigarayı bitirmek zorunda değilsiniz.",
  "Sigara programı sadece bir zamanlayıcı. Henüz içmek istemiyorsanız içmeyin.",
  "Aslında sigara içme isteği uzun sürmez. Sadece 5–10 dakika.",
  "Beklemek ve stresle başa çıkmak normaldir. Sigarasız da normaldir.",
  "Hepimiz reklamlar tarafından kandırıldık. Bunu geride bırakmanın zamanı geldi. Bırakın.",
  "Sadece kendimiz üzerinde çalışarak yeni zirvelere ulaşırız. Bırakıyorsunuz — bununla gurur duyun!",
  "Bıraktığınızda çevrenizdeki insanların ne kadar şaşıracağını hayal edin.",
  "Kağıda sarılmış bir yaprak parçası insanı kontrol eder mi? Hayır!",
  "Her gün kendinizi sınırlayın. Sigarayı yenmenin tek yolu budur.",
  "Pek çok kişi sigarayı ancak sonuçlarıyla yüzleştikten sonra bırakıyor.",
  "Alışkanlığınız değil siz ne zaman sigara içeceğinize karar verdiğinizde artık onun kölesi değilsiniz.",
  "Sigara sinirleri yatıştırmaz. Bu sadece bir pazarlama hilesi.",
  "Sonuna kadar pes etmeyin. Ne tatillerde ne de zor günlerde.",
  "Her zaman hatırlayın — sigarayı bırakmak kişisel hedefiniz. Neredeyse oraya ulaştınız.",
  "Sigara içmek mi istiyorsunuz? 10 dakikalık zamanlayıcı kurun. İstemeyeceksiniz — denenmiş ve doğrulanmış.",
  "Bu kadar para duman olup gidiyor...",
  "Botu kullanmaya başladığınızda sigarayı bırakmaya kesinlikle karar verdiniz. Bırakın. Buna değer.",
  "Kötü alışkanlıklar ruhsal olarak zayıf insanlar içindir. Bu sizin hakkınızda değil.",
  "Botu kullanarak ilerlemenizi takip edin. Bir ayda sizin için ne kadar şey değişti.",
  "İnsanların çoğu sigara içmiyor. Bırakın.",
  "Sigara rahatlama yanılsamasıdır. Aslında vücudunuz toksinlerinden acı çekiyor.",
  "Olumsuzluğu görselleştirin. Sigarada sizi en çok rahatsız eden şeyi hatırlayın.",
  "Daha iyisini hak ediyorsunuz. Sigara içmeyin.",
  "Bu dünya insan hayatları üzerine kurulmuş ama insan başarılarıyla ayakta duruyor.",
  "Sigarayı bırakıyorsunuz! Harika bir iş çıkarıyorsunuz!",
  "Kötü alışkanlıklarla mücadele etme kararlılığı modern insanı tanımlar.",
  "5 dakika içinde sigara içmek istediğinizi unutacaksanız neden sigara programını bozuyorsunuz?",
  "Bazen bir sonraki molayı beklemek ne kadar zor olabiliyor...",
  "Garip ve işe yaramaz bir alışkanlık boş zamanınızı şekillendiriyor mu?",
  "Bıraktığınızda başkaları size örnek olarak bakacak.",
  "Sigara, insanın her zaman kaybettiği bir sistemdir.",
  "İrade gücü spor salonundaki bir kas gibidir. Sigarayı yenin ve başka zorlukları da aşarsınız.",
  "Dumanı üflediğinizde geriye hiçbir şey kalmıyor. Sadece harcanan zaman.",
  "Nikotin bağımlılığı çok, çok sinsi bir düşmandır. Onunla savaşın.",
  "Sigara içmek istiyorsanız başka bir şey düşünmeyi deneyin. Belki yardımcı olur.",
  "Sigara sizin efendiniz değil! İçmek istiyorsanız içersiniz; istemiyorsanız içmezsiniz!",
  "Sadece istemiyorsanız neden sigara içiyorsunuz?",
  "Pes etmeyin. Bir iki ay ve artık sigara içmiyorsunuz. Bu basit.",
  "Zaman zaman istatistiklerinize bakın. Ne kadar para duman oldu şok edici! Komut: /stats",
  "Bir sigara molası yerine ne yapabilirdiniz?",
  "Artık tütün şirketinin bir varlığı değilsiniz.",
  "Vücudunuz nikotinsiz ölmüyor; sadece beyniniz eski oyununu oynamaya çalışıyor.",
  "Sigarayı her ertelediğinizde bağımlılık gücünü kaybediyor.",
  "Sigara sadece toksin ve sıfır fayda.",
  "Sigarayı bırakmaya karar verdiğinizde geleceğinizi korudunuz.",
  "Sigara her şeyi mahveder. İşe yaramaz bir alışkanlık.",
  "Duman solumaya karar veren ne tür zincirler bunlar?",
  "Kaç insanın sigara reklamları tarafından kandırıldığını düşünün.",
  "Aptalca bir alışkanlıktan daha iyi ve daha güçlüsünüz.",
  "Sigarayı bırakmak çoğu insanın düşündüğünden daha kolay.",
  "Size hiçbir şey vermekle kalmayıp sağlığınıza da zarar veren bir nesnenin etrafında yaşamak.",
  "Sigara sağlığı yok eder.",
  "Sigara içme isteği bir zayıflıktır.",
  "Bir alışkanlık neden programınızı dikte etsin? Bırakın!",
  "Sigara geride bırakılması gereken bir şeydir.",
].map(content => `🌟 🌟 🌟 🌟 🌟\n_${content}_`);
