export const youcanEs = [
  "Tú puedes decidir cuándo fumas y cuándo no.",
  "Debes superar tus hábitos. No es difícil.",
  "Puedes saltarte un descanso para fumar de más.",
  "Lo haces por tus seres queridos. Y por ti mismo, en primer lugar.",
  "Ya NO fumas — desde que empezaste a usar el bot.",
  "No es obligatorio fumar el cigarrillo entero si no te apetece.",
  "El horario de fumar es solo un temporizador. Si aún no te apetece, no fumes.",
  "En realidad, las ganas de fumar no duran mucho. Solo 5-10 minutos.",
  "Esperar y lidiar con el estrés es normal. Sin cigarrillos también es normal.",
  "Todos hemos sido engañados por la publicidad. Es hora de librarse de esto. Déjalo.",
  "Solo trabajando en uno mismo alcanzamos nuevas metas. Estás dejando de fumar, ¡tienes de qué estar orgulloso!",
  "Imagina cuánto se sorprenderán los demás cuando lo dejes.",
  "¿Un trozo de hoja envuelto en papel controla a una persona? ¡No!",
  "Cada día límitate. Solo así se puede vencer el tabaco.",
  "Muchos dejan de fumar cuando ya se han enfrentado a las consecuencias.",
  "En cuanto tú decides cuándo fumas, y no el hábito, ya no eres su esclavo.",
  "Fumar no calma los nervios. Es un simple truco publicitario.",
  "No te des tregua hasta el final. Ni en fiestas, ni en días duros.",
  "Recuerda siempre: dejar de fumar es tu meta personal. Ya está cerca.",
  "¿Te entraron ganas de fumar? Pon un temporizador de 10 minutos. Se te pasarán, comprobado.",
  "Tanto dinero en humo...",
  "Cuando empezaste a usar el bot, decidiste firmemente dejar de fumar. Déjalo. Merece la pena.",
  "Los malos hábitos son cosa de personas débiles de espíritu. Eso no va contigo.",
  "Observa tu progreso con la ayuda del bot. Cuánto ha cambiado todo para ti en un mes.",
  "La mayoría de la gente no fuma. Déjalo.",
  "Fumar es una ilusión de relajación. A tu organismo en realidad le sienta mal por sus venenos.",
  "Visualiza lo negativo. Recuerda qué es lo que más te molesta de fumar.",
  "Te mereces algo mejor. No fumes.",
  "Todo este mundo está construido sobre vidas humanas. Pero se sostiene sobre logros humanos.",
  "¡Estás dejando de fumar! ¡Eres increíble!",
  "La firmeza para luchar contra los malos hábitos define a la persona moderna.",
  "¿Para qué romper el horario de fumar si olvidarás que querías fumar en 5 minutos?",
  "A veces es tan difícil esperar al siguiente descanso para fumar...",
  "¿Un hábito extraño e inútil determina tu tiempo libre?",
  "Los demás te verán como un ejemplo cuando lo dejes.",
  "Fumar es un sistema donde la persona siempre pierde.",
  "La fuerza de voluntad es como un músculo en el gimnasio. Si vences el tabaco, podrás vencer otras cosas.",
  "Cuando exhalas el humo, no queda nada. Solo tiempo perdido.",
  "La adicción a la nicotina es un enemigo muy astuto. Lucha.",
  "Si te dan ganas de fumar, intenta pensar en otra cosa. Quizás ayude.",
  "¡El cigarrillo no es tu dueño! Quieres fumas, quieres no.",
  "¿Para qué fumar si simplemente no te apetece?",
  "No te rindas. Un mes o dos y no fumas. Es así de simple.",
  "Echa un vistazo a las estadísticas de vez en cuando. ¡Es terrible cuánto dinero se ha ido al aire! Comando /stats",
  "¿Qué podrías hacer en vez de otro descanso para fumar?",
  "Ya no eres un activo de la compañía tabacalera.",
  "Tu cuerpo no muere sin nicotina, es solo tu cerebro intentando jugar su viejo juego contigo.",
  "Cada vez que pospones fumar, la adicción pierde su fuerza.",
  "El tabaco son puras toxinas y cero beneficio.",
  "Cuando decidiste dejar de fumar, protegiste tu futuro.",
  "Fumar solo lo estropea todo. Hábito inútil.",
  "¿Qué cadenas son esas que deciden que tienes que echar humo?",
  "Piensa en cuánta gente ha sido engañada por la publicidad de cigarrillos.",
  "Eres mejor y más fuerte que un hábito estúpido.",
  "Dejar de fumar es más fácil de lo que mucha gente piensa.",
  "La vida alrededor de un objeto que no solo no aporta nada, sino que arruina la salud.",
  "Los cigarrillos destruyen la salud.",
  "Las ganas de fumar son debilidad.",
  "¿Por qué un hábito debería organizar el horario de tu día? ¡Déjalo!",
  "Fumar es algo que hay que dejar atrás.",
].map(content => `🌟 🌟 🌟 🌟 🌟\n_${content}_`);
